# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text="<a href='javascript:' data-target='myModal'></a>", max_length=128, verbose_name='password'),
        ),
    ]
