# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20170904_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Enrollment', verbose_name='报名表中的学生'),
        ),
    ]
