# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20170909_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_url', models.URLField(verbose_name='附件上传的url')),
                ('study_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.StudyRecord', verbose_name='学习记录')),
            ],
            options={
                'verbose_name_plural': '作业附件',
            },
        ),
    ]
