# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 02:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_auto_20170912_0227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm.can_access_my_class', '访问我的课程'), ('crm.can_access_customer_list', '访问客户库'), ('crm.can_access_customer_detail', '访问客户详情'), ('crm.can_change_customer_detail', '修改客户详情'))},
        ),
    ]
